name: Build DUMB

on: push

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Visual Studio 64-bit",
            os: windows-latest,
            triplet: x64-windows
          }
        - {
            name: "Visual Studio 32-bit",
            os: windows-latest,
            triplet: x86-windows
          }

    steps:
    - uses: actions/checkout@v1

    - name: Configure
      id: vars
      shell: cmd
      run: |
        rem echo ::set-output name=common_options::dumb --triplet ${{ matrix.config.triplet }}
        echo ::set-output name=common_options::zlib --triplet ${{ matrix.config.triplet }}

    - name: Install
      shell: cmd
      run: |
        vcpkg update
        xcopy .github\workflows\dumb %VCPKG_INSTALLATION_ROOT%\ports
        vcpkg install ${{ steps.vars.outputs.common_options }}

    # - name: Logs
    #   if: failure()
    #   shell: cmd
    #   run: |
    #     type C:\vcpkg\buildtrees\dumb\install-${{ matrix.config.triplet }}-dbg-out.log
    #     echo !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    #     type C:\vcpkg\buildtrees\dumb\install-${{ matrix.config.triplet }}-dbg-out-1.log

    - name: Export
      if: always()
      shell: cmd
      run: |
        # vcpkg export ${{ steps.vars.outputs.common_options }} --zip
        md artifact
        xcopy %VCPKG_INSTALLATION_ROOT%\buildtrees\* artifact /s

    - name: Upload
      if: always()
      uses: actions/upload-artifact@v1
      with:
        path: artifact
        name: ${{ matrix.config.triplet }}

