name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Visual Studio 64-bit",
            os: windows-latest,
            build_type: "Release",
            extra_options: "-A x64",
            package_name: "vs_x64"
          }
        - {
            name: "Visual Studio 32-bit",
            os: windows-latest,
            build_type: "Release",
            extra_options: "-A Win32",
            package_name: "vs_win32"
          }
        - {
            name: "Linux GCC",
            os: ubuntu-latest,
            build_type: "Release",
            extra_options: "",
            package_name: "linux_gcc"
          }
        - {
            name: "Linux Clang",
            os: ubuntu-latest,
            build_type: "Release",
            extra_options: "-DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++",
            package_name: "linux_clang"
          }
        - {
            name: "macOS Clang",
            os: macos-latest,
            build_type: "Release",
            extra_options: "",
            package_name: "macos"
          }

    steps:
    - uses: actions/checkout@v1

    - name: Install Dependencies
      shell: bash
      run: |
        mkdir build
        cd build
        if [[ "${{ runner.os }}" == 'Linux' ]]; then
          sudo apt update
          sudo apt install libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-net-dev \
            libpcre3-dev libmad0-dev libfluidsynth-dev libdumb1-dev libvorbis-dev libportmidi-dev
        elif [[ "${{ runner.os }}" == 'macOS' ]]; then
          brew install sdl2 sdl2_image sdl2_mixer sdl2_net pcre mad fluidsynth dumb portmidi
        else
          curl -LO https://libsdl.org/release/SDL2-devel-2.0.10-VC.zip
          7z x SDL2-devel-2.0.10-VC.zip
          curl -LO https://libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.5-VC.zip
          7z x SDL2_image-devel-2.0.5-VC.zip
          curl -LO https://libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.4-VC.zip
          7z x SDL2_mixer-devel-2.0.4-VC.zip
          curl -LO https://libsdl.org/projects/SDL_net/release/SDL2_net-devel-2.0.1-VC.zip
          7z x SDL2_net-devel-2.0.1-VC.zip
        fi

    - name: Configure
      shell: bash
      run: |
        cd build
        if [[ "${{ runner.os }}" == 'Windows' ]]; then
          declare -x SDL2DIR="`pwd`/SDL2-2.0.10"
          declare -x SDL2IMAGEDIR="`pwd`/SDL2_image-2.0.5"
          declare -x SDL2MIXERDIR="`pwd`/SDL2_mixer-2.0.4"
          declare -x SDL2NETDIR="`pwd`/SDL2_net-2.0.1"
        fi
        cmake -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} ${{ matrix.config.extra_options }} ../prboom2

    - name: Build
      shell: bash
      run: |
        cd build
        if [[ "${{ runner.os }}" == 'Windows' ]]; then
          cmake --build . --config ${{ matrix.config.build_type }} -- -maxcpucount -verbosity:minimal
        else
          cmake --build . -- --jobs=2 --keep-going
        fi

    - name: Create Package
      shell: bash
      run: |
        cd build
        mkdir package
        if [[ "${{ runner.os }}" == 'Windows' ]]; then
          cp ${{ matrix.config.build_type }}/prboom-plus.exe ${{ matrix.config.build_type }}/prboom-plus-game-server.exe prboom-plus.wad package
        elif [[ "${{ runner.os }}" == 'macOS' ]]; then
          cp -R Launcher.app package
        else
          cp prboom-plus prboom-plus-game-server prboom-plus.wad package
        fi
        cp config.h package

    - name: Upload Package
      uses: actions/upload-artifact@v1
      with:
        path: build/package
        name: ${{ matrix.config.package_name }}

    - name: List Build Directory
      if: always()
      shell: bash
      run: ls -lR build

# TODO: package artifacts
