name: Windows Dependencies

on:
  push:
    branches:
    - windows_dependencies
  pull_request:
    branches:
    - windows_dependencies

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Visual Studio 64-bit",
            os: windows-latest,
            triplet: x64-windows
          }
        - {
            name: "Visual Studio 32-bit",
            os: windows-latest,
            triplet: x86-windows
          }

    steps:
    - name: Install
      shell: cmd
      run: |
        vcpkg update
        vcpkg install zlib --triplet ${{ matrix.config.triplet }}

    - name: Export
      shell: cmd
      run: |
        vcpkg export zlib --7zip --triplet ${{ matrix.config.triplet }}
        md artifact
        move %VCPKG_INSTALLATION_ROOT%/*.7z artifact

    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        path: artifact
        name: ${{ matrix.config.triplet }}

